# Generated by Django 3.2.7 on 2021-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerlicense',
            name='license_add',
            field=models.IntegerField(default=0),
        ),
    ]
