# Generated by Django 3.2.7 on 2021-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_timerlicense_license_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_name', models.CharField(max_length=100)),
                ('reminder_date', models.DateField()),
                ('reminder_desc', models.TextField(max_length=300)),
                ('reminder_time', models.TimeField()),
                ('reminder_prenotice', models.IntegerField()),
                ('reminder_replay', models.CharField(max_length=30)),
            ],
        ),
    ]
