# Generated by Django 3.2.7 on 2021-09-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_generalreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timerLicense',
        ),
    ]
